[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true

[theme]
base = "dark"
primaryColor = "#F5B544"
backgroundColor = "#080B16"
secondaryBackgroundColor = "#111522"
textColor = "#F0F2F8"
